apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows michelle user to read the cluster nodes
kind: ClusterRoleBinding
metadata:
  name: michelle-rolebinding
subjects:
- kind: User
  name: michelle # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: michelle-role
  apiGroup: rbac.authorization.k8s.io