apiVersion: v1
kind: Config
current-context: kubernetes-admin@kubernetes
clusters:
  - cluster:
      certificate-authority-data: DATA+OMITTED
      server: https://172.17.0.16:6443
    name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED