apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:         # kubectl explain persistentvolume --recursive | less...........then search for /hostPath
    path: /pv/log