apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:          # kubectl explain pod --recursive | less
      - secretRef:
          name: db-secret
