apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:     #it is called "data" in Secret, not spec
  DB_Host: c3FsMDEK     # encode using "echo sql01 | base64"
  DB_User: cm9vdAo=
  DB_Password: UGFzc3dvcmQK


# ------------create secret using imperative way with command--------------------
#   root@controlplane:~# kubectl create secret generic db-secret \                                                         
# > --from-literal=DB_Host=sql01 \
# > --from-literal=DB_User=root \
# > --from-literal=DB_Password=password123